maintainer       "Guilhem Lettron"
maintainer_email "guilhem.lettron@youscribe.com"
license          "Apache 2.0"
description      "Installs/Configures ZTC (Zabbix collection)"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"
supports          "ubuntu", ">= 10.04"
supports          "debian", ">= 6.0"
supports          "redhat", ">= 5.0"
supports          "centos", ">= 5.0"

depends "database", ">= 1.0.0"
depends "mysql", ">= 1.2.0"
depends "ufw",  ">= 0.6.1"
depends "yum"
depends "postgresql"
depends "mercurial"
depends "python"
suggests "windows"
